import Head from "next/head";
import io, { Socket } from "socket.io-client";
import { Button } from "@mui/material";
import { useEffect, useState } from "react";

let socket: Socket;

export default function Home() {
  useEffect(() => {
    fetch("/api/socket").finally(() => {
      socket = io();

      socket.on("connect", () => {
        console.log("connect");
        socket.emit("hello");
      });

      socket.on("hello", (data) => {
        console.log("hello", data);
      });

      socket.on("a user connected", () => {
        console.log("a user connected");
      });

      socket.on("disconnect", () => {
        console.log("disconnect");
      });

      socket.on("testBroadcast", (message) => {
        console.log(message);
      });
    });
  }, []);

  const testSocket = () => {
    socket.emit("test", "Test Message");
  };

  return (
    <>
      <Head>
        <title>Thesis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Socket Test</h1>
        <Button onClick={testSocket} variant="contained">
          TEST SOCKET
        </Button>
      </main>
    </>
  );
}
